# https://www.mkdocs.org/

site_name: Documentation of DPMHM
site_url: https://google.com/
repo_url: https://github.com/yanncalec/dpmhm
site_description: Documentation of dpmhm

# https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
theme:
  name: material
  # name: readthedocs
  language: en

plugins:
  - search
  # # https://github.com/chrieke/mkdocs-exclude-search
  # - exclude-search:
  #     exclude:
  #       - datasets/untested/*
  # https://github.com/apenwarr/mkdocs-exclude
  - exclude:
      glob:
        - datasets/untested/*
  # # Export to pdf
  # - pdf-export
  - with-pdf:  # https://github.com/orzih/mkdocs-with-pdf
      author: Han WANG
      # copyright: 2023 CEA/LIST
      #
      cover: True
      #back_cover: true
      cover_title: 'DPMHM: A python package for machine health monitoring'
      # cover_title: Report for HIASCI GT3
      # cover_subtitle: DPMHM
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      output_path: pdf/document.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
  - bibtex:
      bib_file: docs/HIASCI.bib
      # csl_file: https://github.com/citation-style-language/styles/blob/master/elsevier-harvard.csl
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          # selection:
          #   docstring_style: "numpy"
          rendering:
            show_source: false
      # custom_templates: templates
  # https://github.com/danielfrg/mkdocs-jupyter
  # uncomment to enable online conversion of jupyter notebooks:
  - mkdocs-jupyter:
      # ignore_h1_titles: True
      include_source: True

markdown_extensions:
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  # - Datasets: datasets.md
  # - Models: models.md
  - Usage:
    - datasets.md
    - models.md
    # - rul.md
  - Topics:
    - Overview: topics/mhm.md
    - Feature Extraction: topics/vibration.md
    # - Baseline Methods: topics/baseline.md
    - Architectures:
      # - CNN: topics/architectures/cnn.md
      - Auto-Encoder: topics/architectures/ae.md
      # - DBN: topics/architectures/dbn.md
      # - GAN: topics/architectures/gan.md
      # - RNN: topics/architectures/rnn.md
    # - Transfer Learning: topics/transfer.md
    # - Few-shot Learning: topics/few-shot.md
    # - Representation Learning: topics/representation.md
    # - RUL: topics/rul.md
    - Visualization: topics/visualize.md
    - Advanced Topics:
      - Sensor Fusions: topics/sensors.md
      - Explainability: topics/explainability.md
  - Tutorials:
    # - Overview: tutorials/tuto.md
    # - Datasets:
    # - Models:
    - Installation: notebooks/datasets/installation.ipynb
    - Preprocessing: notebooks/datasets/preprocessing.ipynb
    - Supervised VGGish: notebooks/models/supervised_vggish.ipynb
    - Auto-Encoder: notebooks/models/auto-encoder.ipynb
  - Reference:
    - Datasets:
      - CWRU: datasets/cwru.md
      - datasets/dcase2020.md
      # - datasets/dcase2021.md
      # - datasets/dcase2022.md
      - DIRG: datasets/dirg.md
      - Fraunhofer151: datasets/fraunhofer151.md
      # - Fraunhofer205: datasets/fraunhofer205.md
      # - FEMTO: datasets/femto.md
      # - IMS: datasets/ims.md
      # - Mafaulda: datasets/mafaulda.md
      # - Ottawa: datasets/ottawa.md
      # - Paderborn: datasets/paderborn.md
      # - Phmap2021: datasets/phmap2021.md
      # - SEUC: datasets/seuc.md
      # - XJTU: datasets/xjtu.md
    - Models:
      - VGGish: models/vggish.md
      - SimCLR: models/simclr.md
  # - Misc: --8<-- "README.md"

watch:
  - dpmhm
  - tests

# docs_dir: docs
# site_dir: site
