site_name: dpmhm
site_url: https://google.com/
repo_url: https://github.com/example/repository/

theme:
  name: material
  # name: readthedocs
  language: en

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  # - toc:
  #     permalink: True
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Overview:
    - datasets.md
    # - models.md
  - Dataset:
    - CWRU: datasets/cwru.md
  # - Models:
  # - Home: '../../README.md'
  # - index.md
