[tool.poetry]
name = "dpmhm"
version = "0.1.0"
description = "Diagnostic and Pronostic for Machine Health Monitoring"
authors = ["Han Wang <han.wang.fr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tensorflow = "^2.10.0"
tensorflow_datasets = "^4.7.0"
tensorflow_addons = "^0.18.0"
# tensorflow_probability = "^0.18.0"
# tensorflow_model_optimization = "^0.7.3"
numpy = "^1.23"
librosa = "^0.9.2"
pandas = "^1.5.2"
scikit_image = "^0.19.3"
pydub = "^0.25.1"
# mkdocs_jupyter = ""
# mkdocstrings_python

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
